### ISSUE TITLE
Displayed Page is incorrect

### ISSUE THREAD

**Issue by guest271314** [WebWeWant/webwewant.fyi#16]
Displayed Page is incorrect

![page_1_URL](https://user-images.githubusercontent.com/4174848/65534904-dabed400-deef-11e9-9f92-227dab12f8f9.png)
![page_1_navigation_display](https://user-images.githubusercontent.com/4174848/65534903-da263d80-deef-11e9-94b9-b45e331a805c.png)

Page 8 does not exist

![page_8_404](https://user-images.githubusercontent.com/4174848/65534902-da263d80-deef-11e9-924a-776b4399ac90.png)

**Comment by aarongustafson** [comment]
Must have been a build failure. The site is working now: https://webwewant.fyi/wants/page/1
