### ISSUE TITLE
Vote not displayed at Want #7

### ISSUE THREAD

**Issue by guest271314** [WebWeWant/webwewant.fyi#17]
The vote for [Want 7](https://webwewant.fyi/wants/7/) was cast at https://github.com/WebWeWant/webwewant.fyi/pull/15#issuecomment-531668040

> Will this vote @dsanders11 https://webwewant.fyi/wants/7/ be reflected on the page at Votes: N?

At https://webwewant.fyi/voting/

> These could be hand-crafted webmentions sent from your own site or shares and likes on social media. 

The term "social media" is extremely broad. 

If an individual relied on Wikipedia or Merriam-Webster as a primary source for the definition of the term "social media" GitHub is included in the plain meaning of that term

[Social media (Wikipedia)](https://en.wikipedia.org/wiki/Social_media) 

> Social media are interactive computer-mediated technologies that facilitate the creation and sharing of information, ideas, career interests and other forms of expression via virtual communities and networks.<sup>[[1]](https://en.wikipedia.org/wiki/Social_media#cite_note-Kietzmann-1)</sup> The variety of stand-alone and built-in social media services currently available introduces challenges of definition; however, there are some common features:<sup>[[2]](https://en.wikipedia.org/wiki/Social_media#cite_note-SMDefinition-2)</sup>
> 
> - Social media are interactive Web 2.0 Internet-based applications.<sup>[[2]](https://en.wikipedia.org/wiki/Social_media#cite_note-SMDefinition-2)[[3]](https://en.wikipedia.org/wiki/Social_media#cite_note-Kaplan-3)</sup>
> - User-generated content, such as text posts or comments, digital photos or videos, and data generated through all online interactions, is the lifeblood of social media.<sup>[[2]](https://en.wikipedia.org/wiki/Social_media#cite_note-SMDefinition-2)[[3]](https://en.wikipedia.org/wiki/Social_media#cite_note-Kaplan-3)</sup>
> - Users create service-specific profiles for the website or app that are designed and maintained by the social media organization.<sup>[[2]](https://en.wikipedia.org/wiki/Social_media#cite_note-SMDefinition-2)[[4]](https://en.wikipedia.org/wiki/Social_media#cite_note-boydEllison-4)</sup>
> - Social media facilitate the development of online social networks by connecting a user's profile with those of other individuals or groups. <sup>[[2]](https://en.wikipedia.org/wiki/Social_media#cite_note-SMDefinition-2)[[4]](https://en.wikipedia.org/wiki/Social_media#cite_note-boydEllison-4)</sup>

[social media (Merriam-Webster)](https://www.merriam-webster.com/dictionary/social%20media) 

> **Definition of _social media_**
>
> : forms of electronic communication (such as websites for social networking and microblogging) through which users create online communities to share information, ideas, personal messages, and other content (such as videos)

Therefore the vote for "Want 7" at https://github.com/WebWeWant/webwewant.fyi/pull/15#issuecomment-531668040 should be reflected on the corresponding HTML page.

**Comment by aarongustafson** [comment]
I’ll clarify by saying we pull from [Brid.gy](https://Brid.gy). If they collect from a service, it will be reflected.

**Comment by guest271314** [comment]
The voting scheme appears to be some form of social media gimmick instead of focus on the actual technical "Want" submitted. 

In order to vote an individual would need to sign up for yet another "social media" account where GitHub is already social media. None of this relevant to voting makes any sense.

**Comment by aarongustafson** [comment]
GitHub is supported (per your other bug).
