### ISSUE TITLE
I want a native implementation or API for skip links

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#233]
[Skip links are an important accessibility feature](https://webaim.org/techniques/skipnav/) to improve keyboard navigation.
They are also non-trivial to build; they usually need to be visually hidden and revealed only on focus. This is a challenge in CSS since there is [no elegant way to do it with a single property](https://hugogiraudel.com/2016/10/13/css-hide-and-seek/). They can also be difficult to integrate in existing web designs and layouts.

It would be good to have browsers implement skip links natively. This way, more websites would have skip links, which would drastically improve overall keyboard navigation, and avoid problematic or buggy implementations. Additionally, they would be normalized across websites, automatically in the right language (browser language) and implemented in the browser UI instead of within pages. 

Now figuring out what DOM node is the appropriate container for the main content of the page can be tricky. If that’s not something the browser can easily figure out, this could be provided by the implementor through a `meta` tag. For instance:

```html
<meta name="main-content-selector" content="#main">
```

<hr>

https://webwewant.fyi/wants/5fc8bb41d84cfbab3fb47320/

**Comment by HugoGiraudel** [comment]
I didn’t intend to be an anonymous submitter. This comes from me. 😊
Relevant Twitter thread: https://twitter.com/HugoGiraudel/status/1334433481116569600?s=20

**Comment by carmacleod** [comment]
Skip links are great, but [native landmark navigation](https://webwewant.fyi/wants/5f24adc28dfea402c3830218/) would be even better! :)

**Comment by aarongustafson** [comment]
> I didn’t intend to be an anonymous submitter. This comes from me. 😊

During the initial intake we keep the submitter private and then cross-reference it with the raw data just to make sure folks can remain anonymous is they so desire. :-)

**Comment by aarongustafson** [comment]
Publishing now.
