### ISSUE TITLE
You to expire!

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#240]
---
title: You to expire!
date: 2020-12-06T12:13:59.487Z
submitter: PRIVATE
number: 5fcccb07ed2c2621fd36f97e
tags: [  ]
discussion: https://github.com/WebWeWant/webwewant.fyi/discussions/
status: [ discussing || in-progress || complete ]
related:
  - title:
    url:
    type: [ article || explainer || draft || spec || note || discussion ]
---

I have information that your site is a fraud.  I am working on removing all of you from the 485 dimensions here on Earth. I happen to be the human who people centuries ago believed that the spirit of Jesus Christ was to return in human form to this Earth. One third of the world will be thrown into the central sun.  You will be one of them.  I advise you to prepare for that to happen before spring time of 2021.  This event was to happen in 2018  when the eight planets were to align with the sun(which happens every century). I am not going to reveal the reason why it did not occur at that time.  So prepare yourselves for what will be called, "Heaven on Earth."

<hr>

If posted, this will appear at https://webwewant.fyi/wants/5fcccb07ed2c2621fd36f97e/

**Comment by guest271314** [comment]
The post does not describe any articulated want. I will not go too in-dept here as to when, where, how, and why the created creature "Jesus the Christ" came about directly from the previous created creature "Oserapis", later shortened to "Serapis". I suggest that you carefully read _The Historical Origin of Christianity_ by Walter Williams for your own edification.

**Comment by aarongustafson** [comment]
> The post does not describe any articulated want. I will not go too in-dept here as to when, where, how, and why the created creature "Jesus the Christ" came about directly from the previous created creature "Oserapis", later shortened to "Serapis". I suggest that you carefully read _The Historical Origin of Christianity_ by Walter Williams for your own edification.

To be clear, this did not originate from me, they all come in from the site, with me as the listed creator.

**Comment by guest271314** [comment]
> To be clear, this did not originate from me, they all come in from the site, with me as the listed creator.

I get that. 

There is a record by Prodigy of Mobb Deep (R.I.P.) on their masterpiece album _Hegelian Dialectic_, _Broken Apple_ that includes lyrics that go something like:

_Fuck, just look at yourself
You can't fathom your own operating system

Fuck a MacBook, I'll take a real book any day
And fuck your automation, give me a human being_

Consider those lyrics very carefully.

It is not possible to "offend" me. I use the scientific method, and am well-versed in ancient and modern history and politics. 

The treatise that I referenced documents the politcal machinations that lead to the hearsay they are repeating. I suppose they really did want something, and did not know that they would find the right one, to, without rancor, cite resources that might help eliminate at least one of the sources of their apparent anxiety.

**Comment by aarongustafson** [comment]
@guest271314 I’m not sure what any of this has to do with Web We Want. I’ll be locking this conversation and deleting all comments as they have no bearing on this spam submission.
