### ISSUE TITLE
lear how to  web

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#252]
---
title: lear how to  web
date: 2020-12-17T05:19:27.635Z
submitter: PRIVATE
number: 5fdaea5f3a02984901607b50
tags: [  ]
discussion: https://github.com/WebWeWant/webwewant.fyi/discussions/
status: [ discussing || in-progress || complete ]
related:
  - title:
    url:
    type: [ article || explainer || draft || spec || note || discussion ]
---

get info to get on line

<hr>

If posted, this will appear at https://webwewant.fyi/wants/5fdaea5f3a02984901607b50/

**Comment by guest271314** [comment]
Not a Web want.
