### ISSUE TITLE
Add flags in HTML input element to define validation rules for email address

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#262]
---
title: Add flags in HTML input element to define validation rules for email address
date: 2021-01-12T16:50:37.614Z
submitter: PRIVATE
number: 5ffdd35dd78fb01e226bfeff
tags: [  ]
discussion: https://github.com/WebWeWant/webwewant.fyi/discussions/
status: [ discussing || in-progress || complete ]
related:
  - title:
    url:
    type: [ article || explainer || draft || spec || note || discussion ]
---

There are many possibilities for valid email address according to what websites consider  parts of an email address valid when registering users. Most of websites want that user provide email address which is most generally used, for example - xyz@example.com. From this example, what a most generally used email address consist is - a user name / id (xyz) and a domain name with TLD (example.com). However, a valid email address may contain many other parts and may even omit TLD. In a valid email address, the domain may be an IP address of version 4 or 6, the id part may contain "+" (plus) sign which is used for aliasing, white-space, quote, comment and more. But website wouldn't generally like to accept all these. As well as, sometimes the users are forgetting to specifying TLD.

So, my suggestion is to introduce flags through attribute or attribute values using which the developers should be able to specify what part of an email address must or must not contain. For example, if flag "require-TLD" is specified as an attribute or as a value in a specific attribute in an `<input type="email">` element then browser must not consider input email address valid if it doesn't contain TLD at the end.

<hr>

If posted, this will appear at https://webwewant.fyi/wants/5ffdd35dd78fb01e226bfeff/

**Comment by nikunjbhatt** [comment]
There is a problem in all submissions / issues / wants posted through the webwewant.fyi if there is HTML code. HTML code is not showing up in the issue / comments in GitHub. When submitting it to the GitHub through back-end code, the HTML needs to be encoded. As the issues / wants are related to web and HTML, there is good possibility that it may contain HTML code and so it should be encoded to show the code properly in issues / comments. My suggestion is to encode at least left-angle-bracket / less-than-sign / "<" to \&lt; to resolve this issue.

In the main/first comment, **&lt;input type="email">** is missing from the last sentence. The last sentence should read:
For example, if flag "require-TLD" is specified as an attribute or as a value in a specific attribute in an **&lt;input type="email">** element then browser must not consider input email address valid if it doesn't contain TLD at the end.

**Comment by aarongustafson** [comment]
> There is a problem in all submissions / issues / wants posted through the webwewant.fyi if there is HTML code. HTML code is not showing up in the issue / comments in GitHub. When submitting it to the GitHub through back-end code, the HTML needs to be encoded. As the issues / wants are related to web and HTML, there is good possibility that it may contain HTML code and so it should be encoded to show the code properly in issues / comments. My suggestion is to encode at least left-angle-bracket / less-than-sign / "<" to &lt; to resolve this issue.
> 
> In the main/first comment, **<input type="email">** is missing from the last sentence. The last sentence should read:
> For example, if flag "require-TLD" is specified as an attribute or as a value in a specific attribute in an **<input type="email">** element then browser must not consider input email address valid if it doesn't contain TLD at the end.

It’s a markdown thing, but we clean it up manually when they come in. :-)
