### ISSUE TITLE
title deleted by WWW admin

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#272]
---
title: removed 
date: 2021-01-26T19:53:33.272Z
submitter: PRIVATE
number: 6010733d08c09a1aa89964b7
tags: [  ]
discussion: https://github.com/WebWeWant/webwewant.fyi/discussions/
status: [ discussing || in-progress || complete ]
related:
  - title:
    url:
    type: [ article || explainer || draft || spec || note || discussion ]
---

<hr>

If posted, this will appear at https://webwewant.fyi/wants/6010733d08c09a1aa89964b7/

**Comment by ststimac** [comment]
Spam + removed all content to the link that was submitted
