### ISSUE TITLE
Wants discussions

### ISSUE THREAD

**Issue by Malvoz** [WebWeWant/webwewant.fyi#3]
Will discussions on Wants happen internally, or perhaps each Want should have it's unique issue for discussion in this repo?

**Comment by aarongustafson** [comment]
That’s a good question. I hadn’t thought much about it yet as we’ve been focused on the events as an engagement tool, but I think it’s worth considering. We have been discussing adding a voting mechanism to this site as well (implementation TBD). More substantive discussions might be better had within the context of WICG, which has Discourse for that very purpose.

**Comment by adrianhopebailie** [comment]
I just submitted #9 

Couldn't the discussion (at least some of it) happen in that PR?

**Comment by aarongustafson** [comment]
Yep. Thanks!
