### ISSUE TITLE
How should we indicate a want is being acted upon or has been completed?

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#32]
Just planning ahead here…

Would it make sense to add a progress field to the front matter?

```yml
status: [ discussing || in-progress || complete ]
```

We’d want some way of indicating this information within the individual want page and in the want collection pages. It might also make sense (at some point) to build out a specific page for each of the status types so folks can look at that.

**Comment by marcoscaceres** [comment]
No objections from me. Sounds sensible.

**Comment by bkardell** [comment]
For some things this is kind of straightforward and seems fine.   Though, I feel like already we probably need one more - some kind of 4th 'probably not' or redirection ability.  I could be over-thinking it, but I worry also that it seems inevitable that some of these might not be quite so straightforward. If you get 1/3 of a 'want' in an entirely different shape, 1/3 is punted to 'maybe later' and the remaining 1/3 is 'that is definitely not going to happen' - what's status is it in?

**Comment by aarongustafson** [comment]
@bkardell We could piggyback on @marcoscaceres’ [suggestion of "abandoned"](https://github.com/WebWeWant/webwewant.fyi/issues/31#issuecomment-594460634) from the other discussion.

**Comment by bkardell** [comment]
yeah... idk.  Wants seem somewhat not easy to connect to any easy definition of done to me.  I think maybe linking to concrete proposals, and mentioning the proposal's status is better?

**Comment by aarongustafson** [comment]
Perhaps. What do others think?

Also, what would make sense for things like DevTools or general browser UX suggestions? We could track signal from the various engines like we do in the manifest repo. Any other examples of similar approaches?

**Comment by aarongustafson** [comment]
I’ve implemented this alongside related links
