### ISSUE TITLE
New want: don't touch them you don't know what your messing with

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#56]
---
title: don't touch them you don't know what your messing with
date: 2020-06-09T10:08:48.742Z
submitter: PRIVATE
number: 5edf5fb09234a01c3e1c0a6d
tags: []
---

that i have ride on a space ship- that is a battle ship- so human don't take care of my aliens of my kid you r messing with now

**Comment by bkardell** [comment]
...... ?
