### ISSUE TITLE
New want: I want to be able to filter my network requests based off of address + port

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#70]
---
title: I want to be able to filter my network requests based off of address + port
date: 2020-09-15T01:06:06.049Z
submitter: PRIVATE
number: 5f60137e0a73661227a025fa
tags: []
---

This is a feature that Firefox has -- using a regex filter I can filter my network tab to something like `regexp:localhost:<port>`, when I attempt the same filtering on chrome/chromium based browsers (edge, opera), the filter fails, they do have a way to filter by domain but that doesn't include port.

Currently I don't work around this when not using Firefox, I just suffer https://giphy.com/gifs/AIo1UGpjYue0o

(it would also be nice to be able to open the network tab in a drawer, similar to the console, but currently I just log my network requests to the console, when I need the network tab open alongside the debugger, this works _super_ well as is)

**Comment by mahmudzero** [comment]
submitted by me via form on website

**Comment by captainbrosset** [comment]
Thanks for filing @mahmudzero!

> it would also be nice to be able to open the network tab in a drawer, similar to the console

This is now possible in Edge and Chrome (Canary or Beta only I think right now): right click on a tab and select "move to bottom".

> using a regex filter I can filter my network tab to something like `regexp:localhost:<port>`

This makes a lot of sense to me, and Chromium-based browsers do support regex search in the Network tab already. Try with `/localhost:[0-9]+/` for example. It doesn't work like in Firefox where the `regexp:` prefix is needed. Instead you have to wrap the expression in `/` like in JavaScript.

**Comment by aarongustafson** [comment]
Seems like this exists, but we could use some better dev docs talking about it.

Adding @hxlnt
