### ISSUE TITLE
New want: Every time I try to win $50,000 prize the computer has my email spelled right. Ever y time I enter it , the computer says it is wrong. No one will fix it. I deserve the $50,000!! 

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#73]
---
title: Every time I try to win $50,000 prize the computer has my email spelled right. Ever y time I enter it , the computer says it is wrong. No one will fix it. I deserve the $50,000!! 
date: 2020-09-26T19:27:11.002Z
submitter: PRIVATE
number: 5f6f960fe8021c785279989d
tags: []
---

How is it impacting my work? It's keeping me from winning the $50.000 every time I try for it. I am a VIP and would love to win something ($50,000 or a 2020 Corvette would be nice!!!)
Sharon Willmann

**Comment by captainbrosset** [comment]
Spam.
