### ISSUE TITLE
Provide public status of submissions

### ISSUE THREAD

**Issue by guest271314** [WebWeWant/webwewant.fyi#8]
Submitted five proposals today. No email confirmation of receipt of the proposals have occurred. There does not appear to be any means of referencing a submission or the current status of a submission. 

- Notify users who submit their proposal that the same was actually received. 
- Publish a list of submissions.
- Provide some means of referencing the submission.

**Comment by aarongustafson** [comment]
I’m running a backlog of about 50 submissions. I promise we’ll get to you soon. I’ve been doing it mostly on my own, but I have others joining in to help now. More soon.

**Comment by aarongustafson** [comment]
Just an update on this: We have begun rolling out status badges as well as related specs, etc. in some of the wants. We’ll keep adding to them.
